#
#	compilation parameters for SNAP Python
#

UNAME := $(shell uname)
SETUP = setup.py

ifeq ($(UNAME), Linux)
  # Linux flags
  SWIGFLAGS += -D_CMPWARN -D__stdcall -DSW_SNAPPY -D_OPENMP -DNONUMPY -DUSE_OPENMP -DGCC_ATOMIC
  CXXFLAGS += -fPIC -D__STDC_LIMIT_MACROS -DSW_SNAPPY -fopenmp
  MANIFEST = MANIFEST.nx
  MANIFEST_IN = MANIFEST.in.nx
  PYTHON = python
  PYTHON3 = python3
  # SNAP_PY is set externally for the manylinux1 environment
  ifeq ($(SNAP_PY), 3.9)
    IFLAGS3 = -I/opt/python/cp39-cp39/include/python3.9
    LDFLAGS3 += -shared -fopenmp
    PYTHON3 = /opt/python/cp39-cp39/bin/python3
  else ifeq ($(SNAP_PY), 3.8)
    IFLAGS3 = -I/opt/python/cp38-cp38/include/python3.8
    LDFLAGS3 += -shared -fopenmp
    PYTHON3 = /opt/python/cp38-cp38/bin/python3
  else ifeq ($(SNAP_PY), 3.7)
    IFLAGS3 = -I/opt/python/cp37-cp37m/include/python3.7m
    LDFLAGS3 += -shared -fopenmp
    PYTHON3 = /opt/python/cp37-cp37m/bin/python3
  else ifeq ($(SNAP_PY), 3.6)
    IFLAGS3 = -I/opt/python/cp36-cp36m/include/python3.6m
    LDFLAGS3 += -shared -fopenmp
    PYTHON3 = /opt/python/cp36-cp36m/bin/python3
  else ifeq ($(SNAP_PY), 3.5)
    IFLAGS3 = -I/opt/python/cp35-cp35m/include/python3.5m
    LDFLAGS3 += -shared -fopenmp
    PYTHON3 = /opt/python/cp35-cp35m/bin/python3
  else ifeq ($(SNAP_PY), 2.7m)
    IFLAGS = -I/opt/python/cp27-cp27m/include/python2.7
    LDFLAGS += -shared -fopenmp
    PYTHON = /opt/python/cp27-cp27m/bin/python2
  else ifeq ($(SNAP_PY), 2.7mu)
    IFLAGS = -I/opt/python/cp27-cp27mu/include/python2.7
    LDFLAGS += -shared -fopenmp
    PYTHON = /opt/python/cp27-cp27mu/bin/python2
  else
    IFLAGS ?= -I/usr/include/python2.6 -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include
    IFLAGS3 ?= -I/usr/local/include/python3.7m  -I/usr/include/python3.7m
    IFLAGS3 += -I/usr/local/include/python3.6m  -I/usr/include/python3.6m
    IFLAGS3 += -I/usr/local/include/python3.5m  -I/usr/include/python3.5m
    LDFLAGS += -shared -fopenmp
    LDFLAGS3 += -shared -fopenmp
  endif
else ifeq ($(UNAME), Darwin)
  # OS X flags
  CC = clang++
  CXX = clang++
  SWIGFLAGS += -D_CMPWARN -D__stdcall -DSW_SNAPPY -DNONUMPY
  CXXFLAGS = -std=c++98 -fwrapv -w -O3 -DNDEBUG -DNOMP -DSW_SNAPPY
  CXXFLAGS += -DSW_SNAPPY
  CXXFLAGS += -fexec-charset=UTF-8 -finput-charset=UTF-8 -DCHAR_MIN=0 -DCHAR_MAX=127
  IFLAGS3 = -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13
  LDFLAGS3 = -L/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/lib/python3.13/config-3.13-darwin -ldl -framework CoreFoundation -bundle -undefined dynamic_lookup

  MANIFEST = MANIFEST.mac
  MANIFEST_IN = MANIFEST.in.nx
  PYTHON = python
  PYTHON3 = python3
  # IFLAGS = -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include
  # IFLAGS3 = $(IFLAGS)
  LDFLAGS  = -bundle -undefined dynamic_lookup
  LDFLAGS += -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/openssl@1.1/lib
  LDFLAGS3 = $(LDFLAGS)
  # SNAP_PY is set externally for the python build environment
  ifeq ($(SNAP_PY), 2.7)
    PYPATH = /Users/rok/.pyenv/versions/2.7.18
    CXXFLAGS += -fno-strict-aliasing
    IFLAGS += -I$(PYPATH)/include/python2.7
    LDFLAGS += -L$(PYPATH)/lib
  else ifeq ($(SNAP_PY), 3.5)
    PYPATH = /Users/rok/.pyenv/versions/3.5.10
    IFLAGS3 += -I$(PYPATH)/include/python3.5m
    LDFLAGS3 += -L$(PYPATH)/lib
  else ifeq ($(SNAP_PY), 3.6)
    PYPATH = /Users/rok/.pyenv/versions/3.6.12
    IFLAGS3 += -I$(PYPATH)/include/python3.6m
    LDFLAGS3 += -L$(PYPATH)/lib
  else ifeq ($(SNAP_PY), 3.7)
    PYPATH = /Users/rok/.pyenv/versions/3.7.9
    IFLAGS3 += -I$(PYPATH)/include/python3.7m
    LDFLAGS3 += -L$(PYPATH)/lib
  else ifeq ($(SNAP_PY), 3.8)
    PYPATH = /Users/rok/.pyenv/versions/3.8.6
    IFLAGS3 += -I$(PYPATH)/include/python3.8
    LDFLAGS3 += -L$(PYPATH)/lib
  else ifeq ($(SNAP_PY), 3.9)
    PYPATH = /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
    IFLAGS3 += -I$(PYPATH)/include/python3.9
    LDFLAGS3 += -L$(PYPATH)/lib
    LIBS = -lpython3.9
  else

    # the build environment is not specified, try to figure out the parameters
    PYTHON3        := $(shell which python3)
    PYTHON3_CONFIG := $(shell \
        command -v python3-config >/dev/null 2>&1 && echo python3-config || \
        command -v python3.13-config >/dev/null 2>&1 && echo python3.13-config \
    )
    #ifeq ($(shell command -v $(PYTHON3_CONFIG) >/dev/null 2>&1 && echo OK),OK)
    #  IFLAGS3  := $(shell $(PYTHON3_CONFIG) --includes)
    #  LDFLAGS3 := $(shell $(PYTHON3_CONFIG) --ldflags) -bundle -undefined dynamic_lookup
    #else
    #  $(error "neither python3-config nor python3.10-config found (looking at $$PATH)")
    #endif

    # Detect architecture
    UNAME_M := $(shell uname -m)
    ifeq ($(UNAME_M), arm64)
      ARCHFLAGS := -mmacosx-version-min=15.0
    else
      echo "PROBBBBLEMMMM"
      ARCHFLAGS := -mmacosx-version-min=10.9
    endif
    LDFLAGS3 += $(ARCHFLAGS) -arch arm64
  endif

  # SWIG for Python3
  SWIGFLAGS3 += $(SWIGFLAGS)
  SWIGFLAGS3 += -DCHAR_MIN=0 -DCHAR_MAX=127

else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  SWIGFLAGS += -D_CMPWARN -D__stdcall -DSW_SNAPPY -DNONUMPY
  CXXFLAGS += -shared -D__STDC_LIMIT_MACROS -DSW_SNAPPY
  CXXFLAGS += -arch arm64
  LIBS += -lpython2.6
  MANIFEST = MANIFEST.win
  MANIFEST_IN = MANIFEST.in.win

  ifeq ($(SNAP_PY), 2.7)
    PYTHON = /cygdrive/c/Python27/python
  else ifeq ($(SNAP_PY), 3.5)
    PYTHON = /cygdrive/c/Program\ Files/Python35/python
  else ifeq ($(SNAP_PY), 3.6)
    PYTHON = /cygdrive/c/Program\ Files/Python36/python
  else ifeq ($(SNAP_PY), 3.7)
    PYTHON = /cygdrive/c/Program\ Files/Python37/python
  else ifeq ($(SNAP_PY), 3.8)
    PYTHON = /cygdrive/c/Program\ Files/Python38/python
  else ifeq ($(SNAP_PY), 3.9)
    PYTHON = /cygdrive/c/Program\ Files/Python39/python
  endif
else
  PYTHON = "/cygdrive/c/Program\ Files/Python37/python"
endif

SWIGFLAGS3 += $(SWIGFLAGS)

